name: CI/CD Pipeline

on:
  push:
    branches: [ type-dasher-prod ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/first_real_laravel_docker_projcet/
            git pull origin type-dasher-prod
            docker-compose up --build -d
            docker-compose exec app composer install
            docker-compose exec app chmod 777 -R ./
            docker-compose exec app php artisan migrate --force
            docker-compose exec app npm install
            docker-compose exec app npm run build
            docker-compose exec app cp /var/www/public/.vite/manifest.json /var/www/public/manifest.json
