name: CI/CD Pipeline

on:
  push:
    branches: [ type-dasher-prod ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/first_real_laravel_docker_projcet/
            git pull origin type-dasher-prod
            cp .env.example .env
            sed -i 's/#\?\s*DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
            sed -i 's/#\?\s*DB_PORT=.*/DB_PORT=3306/' .env
            sed -i 's/#\?\s*DB_HOST=.*/DB_HOST=db/' .env
            sed -i 's/#\?\s*DB_PASSWORD=.*/DB_PASSWORD=root/' .env
            sed -i 's/#\?\s*DB_DATABASE=.*/DB_DATABASE=lardocker/' .env
            sed -i 's/#\?\s*DB_USERNAME=.*/DB_USERNAME=root/' .env
            sed -i 's/#\?\s*APP_ENV=.*/APP_ENV=production/' .env
            docker-compose up
